// Layer 1: Scenarios & Lords Data
// ⚠️ 核心基准：不触碰地图坐标

const SCENARIOS = [
    { id: 184, year: 184, title: "黄巾之乱", desc: "苍天已死，黄天当立。乱世开启。" },
    { id: 190, year: 190, title: "讨伐董卓", desc: "十八路诸侯会盟，群雄并起。" },
    { id: 195, year: 195, title: "群雄并起", desc: "吕布袭徐州，孙策崛起江东，天下分崩。" },
    { id: 200, year: 200, title: "官渡之战", desc: "曹操 vs 袁绍，北方霸主之争。" },
    { id: 208, year: 208, title: "赤壁之战", desc: "孙刘联手抗曹，火烧赤壁定三分。" },
    { id: 215, year: 215, title: "湘水划界", desc: "刘备取益州，孙刘以湘水为界，三国格局初现。" },
    { id: 220, year: 220, title: "三分天下", desc: "魏蜀吴鼎立，帝王基业成型。" },
    { id: 249, year: 249, title: "高平陵之变", desc: "司马懿夺权，后期风云再起。" },
    { id: 263, year: 263, title: "魏灭蜀之战", desc: "司马昭三路伐蜀，邓艾偷渡阴平，蜀汉危在旦夕。" }
];

// 主公数据配置
// 肖像路径约定：images/portraits/{id}.png (例如 images/portraits/liu_bei.png)
const SCENARIO_LORDS = {    184: [
        { id: "zhang_jiao", name: "张角", faction: "黄巾", color: "#FBBF24", difficulty: "极难", desc: "苍天已死，黄天当立",
            cities: ["ye","nanpi","jizhou_cheng","qinghe","bohai","pingyuan","liyang","zhending","beiping","jizhou","zhuojun","yuyang","shangdang","pingcheng","yanmenguan","baima","yanzhou","dingtao","jinan","linzi","penglai","xuzhou","peixian","huaiyin"] },
        { id: "zhang_bao", name: "张宝", faction: "黄巾", color: "#FB923C", difficulty: "极难", desc: "黄巾南翼，地公将军",
            cities: ["yingchuan","guandu","runan","xuchang","qiaojun","nanyang","wancheng","xinye","xiangyang","guangling","jianye"] },
        { id: "zhang_liang", name: "张梁", faction: "黄巾", color: "#A16207", difficulty: "极难", desc: "黄巾东翼，人公将军",
            cities: ["baqiu","changsha","guiyang","wuling","langya","chibi","shouchun","hefei","jiangling","gongan","huarong"] },
        { id: "he_jin", name: "何进", faction: "汉朝廷", color: "#DC2626", difficulty: "简单", desc: "大将军，掌控朝政",
            cities: ["luoyang","chang_an","tongguan","wuguan","hongnong","hulao","wuzhangyuan","xianyang","chencang","hedong"] },
        { id: "liu_bei", name: "刘备", faction: "汉朝廷", color: "#F59E0B", difficulty: "极难", desc: "白手起家，桃园结义",
            cities: ["daijun","yiling"] },
        { id: "cao_cao", name: "曹操", faction: "汉朝廷", color: "#7C3AED", difficulty: "困难", desc: "骑都尉，剿匪起家",
            cities: ["chenliu"] },
        { id: "sun_jian", name: "孙坚", faction: "汉朝廷", color: "#4CAF50", difficulty: "困难", desc: "长沙太守，讨黄巾先锋",
            cities: ["jiangxia","caisang","lujiang"] },
        { id: "dong_zhuo", name: "董卓", faction: "汉朝廷", color: "#B91C1C", difficulty: "简单", desc: "西凉军阀，兵强马壮",
            cities: ["liangzhou","zhangye","jiuquan","dunhuang","longxi","anding","qishan","jieting","shangjun"] },
        { id: "lu_zhi", name: "卢植", faction: "汉朝廷", color: "#3B82F6", difficulty: "困难", desc: "镇压黄巾主帅",
            cities: ["wuhuan","lelang","liaodong","bingzhou","beihai"] },
        { id: "huangfu_song", name: "皇甫嵩", faction: "汉朝廷", color: "#2563EB", difficulty: "困难", desc: "讨伐黄巾主力",
            cities: ["yuzhang","poyang","luling","jianan","quanzhou","yizhou","shangyong","chengdu","mianzhu","zitong"] },
        { id: "zhu_jun", name: "朱儁", faction: "汉朝廷", color: "#1D4ED8", difficulty: "困难", desc: "讨伐黄巾",
            cities: ["jiangyou","langzhong","baidi","wuyang","hanzhong","jiamengguan","jiangzhou"] },
        { id: "ma_teng", name: "马腾", faction: "西凉", color: "#6B7280", difficulty: "困难", desc: "西凉铁骑",
            cities: ["tianshui","wudu","yinping","jianmen","xicheng"] },
        { id: "gongsun_zan", name: "公孙瓒", faction: "幽州", color: "#0284C7", difficulty: "困难", desc: "白马义从雏形",
            cities: ["xiapi"] },
        { id: "shi_xie", name: "士燮", faction: "交州", color: "#475569", difficulty: "困难", desc: "交州太守，偏安一隅",
            cities: ["nanhai","guilin","jiaozhi","yazhou"] },
        { id: "meng_huo", name: "孟获", faction: "南蛮", color: "#92400E", difficulty: "极难", desc: "南蛮王，偏远割据",
            cities: ["baishui","yongan","yunnan","jianning"] },
        { id: "xiongnu", name: "南匈奴", faction: "匈奴", color: "#374151", difficulty: "极难", desc: "北方游牧，边患不断",
            cities: ["wuyuan","yinchuan"] },
        { id: "yuan_shu", name: "袁术", faction: "汉朝廷", color: "#EA580C", difficulty: "困难", desc: "南阳太守，野心勃勃",
            cities: ["wujun","kuaiji","danyang"] }
    ],
    190: [
        { id: "dong_zhuo", name: "董卓", faction: "汉朝廷", color: "#DC2626", difficulty: "简单", desc: "把持朝政，天下共击之",
            cities: ["luoyang","chang_an","tongguan","wuguan","hongnong","hulao","wuzhangyuan","xianyang","chencang","hedong","xicheng","anding","shangjun","guandu","xuchang","yingchuan","qishan"] },
        { id: "han_fu", name: "韩馥", faction: "冀州", color: "#F59E0B", difficulty: "普通", desc: "冀州牧，袁绍顶头上司",
            cities: ["ye","nanpi","jizhou_cheng","qinghe","liyang","zhending","jizhou","daijun","zhuojun","pingcheng","yanmenguan"] },
        { id: "cao_cao", name: "曹操", faction: "曹操", color: "#7C3AED", difficulty: "极难", desc: "陈留起兵，实力微弱",
            cities: ["chenliu","yanzhou","dingtao","baima"] },
        { id: "yuan_shao", name: "袁绍", faction: "袁绍", color: "#4682B4", difficulty: "困难", desc: "渤海太守，关东盟主",
            cities: ["jinan","linzi","langya","bohai"] },
        { id: "yuan_shu", name: "袁术", faction: "袁术", color: "#EA580C", difficulty: "普通", desc: "南阳太守，野心勃勃",
            cities: ["nanyang","wancheng","xinye","qiaojun","runan","shouchun","hefei","lujiang","caisang"] },
        { id: "sun_jian", name: "孙坚", faction: "孙氏", color: "#4CAF50", difficulty: "困难", desc: "长沙太守，讨董先锋",
            cities: ["changsha","guiyang","wuling","baqiu","chibi"] },
        { id: "liu_biao", name: "刘表", faction: "荆州", color: "#009688", difficulty: "困难", desc: "新任刺史，根基未稳",
            cities: ["xiangyang","jiangxia","shangyong","jiangling","gongan","huarong","yiling"] },
        { id: "ma_teng", name: "马腾", faction: "西凉", color: "#57534E", difficulty: "困难", desc: "西凉铁骑，虎视中原",
            cities: ["wudu","longxi","liangzhou","zhangye","jiuquan","dunhuang"] },
        { id: "liu_zhang", name: "刘璋", faction: "益州", color: "#92400E", difficulty: "普通", desc: "益州牧，暗弱之主",
            cities: ["chengdu","mianzhu","zitong","jiangyou","langzhong","jiangzhou","baidi","wuyang"] },
        { id: "zhang_lu", name: "张鲁", faction: "汉中", color: "#8B5CF6", difficulty: "困难", desc: "五斗米道，割据汉中",
            cities: ["hanzhong","jiamengguan","yinping","jianmen","baishui"] },
        { id: "gongsun_zan", name: "公孙瓒", faction: "公孙瓒", color: "#5F9EA0", difficulty: "困难", desc: "白马义从，威震幽州",
            cities: ["beiping","yuyang","liaodong","lelang","wuhuan"] },
        { id: "tao_qian", name: "陶谦", faction: "徐州", color: "#6B7280", difficulty: "普通", desc: "徐州牧，仁厚长者",
            cities: ["xuzhou","peixian","xiapi","huaiyin","guangling"] },
        { id: "shi_xie", name: "士燮", faction: "交州", color: "#06B6D4", difficulty: "困难", desc: "交州太守，偏安一隅",
            cities: ["nanhai","guilin","jiaozhi","yazhou"] },
        { id: "meng_huo", name: "孟获", faction: "南蛮", color: "#B45309", difficulty: "极难", desc: "南蛮王，偏远割据",
            cities: ["jianning","yunnan","yongan"] },
        { id: "kong_rong", name: "孔融", faction: "北海", color: "#A3E635", difficulty: "困难", desc: "北海太守，名士风流",
            cities: ["beihai","penglai","quanzhou"] },
        { id: "zhang_yan", name: "张燕", faction: "黑山", color: "#78716C", difficulty: "极难", desc: "黑山军首领",
            cities: ["yizhou","poyang","bingzhou","shangdang"] },
        { id: "liu_dai", name: "刘岱", faction: "兖州", color: "#C084FC", difficulty: "普通", desc: "兖州刺史",
            cities: ["danyang","kuaiji","jianye","jianan","yuzhang","luling","wujun"] },
        { id: "han_sui", name: "韩遂", faction: "凉州", color: "#FB923C", difficulty: "困难", desc: "凉州叛军",
            cities: ["tianshui","jieting"] },
        { id: "xiongnu", name: "南匈奴", faction: "匈奴", color: "#6B7280", difficulty: "极难", desc: "北方游牧，边患不断",
            cities: ["wuyuan","yinchuan"] },
        { id: "liu_bei", name: "刘备", faction: "刘备", color: "#F59E0B", difficulty: "极难", desc: "平原令，仁义之名",
            cities: ["pingyuan"] }
    ],
    195: [
        { id: "cao_cao", name: "曹操", faction: "魏", color: "#7C3AED", difficulty: "困难", desc: "刚平兖州，迎献帝前夕",
            cities: ["yingchuan","guandu","xuchang","qiaojun","baima","yanzhou","chenliu","dingtao","luoyang","chang_an","chencang","hedong","hongnong","wuguan","tongguan","hulao","shouchun","hefei","beiping","yuyang","zhending","liyang","xianyang","wuzhangyuan","shangdang"] },
        { id: "yuan_shao", name: "袁绍", faction: "袁绍", color: "#4682B4", difficulty: "简单", desc: "北方霸主，四世三公",
            cities: ["ye","nanpi","jizhou_cheng","qinghe","bohai","pingyuan","beihai","penglai","linzi","jinan","jizhou","daijun","zhuojun","liaodong","lelang","wuhuan","bingzhou","pingcheng","yanmenguan","shangjun"] },
        { id: "yuan_shu", name: "袁术", faction: "袁术", color: "#EA580C", difficulty: "普通", desc: "占据淮南，称帝野心",
            cities: ["runan","guangling","yizhou","chibi"] },
        { id: "lv_bu", name: "吕布", faction: "吕布", color: "#E11D48", difficulty: "困难", desc: "袭取徐州，武力绝伦",
            cities: ["xuzhou","xiapi","langya","peixian","huaiyin","yiling"] },
        { id: "liu_bei", name: "刘备", faction: "刘备", color: "#F59E0B", difficulty: "极难", desc: "败走汝南，四处流浪",
            cities: ["nanyang","jiangxia","shangyong","jiamengguan"] },
        { id: "sun_ce", name: "孙策", faction: "孙氏", color: "#4CAF50", difficulty: "普通", desc: "小霸王，崛起江东",
            cities: ["jianye","wujun","kuaiji","caisang","danyang","lujiang","yuzhang","poyang","quanzhou","jianan","luling"] },
        { id: "liu_biao", name: "刘表", faction: "荆州", color: "#009688", difficulty: "普通", desc: "荆州之主，守成之主",
            cities: ["xiangyang","jiangling","gongan","huarong","baqiu","changsha","guiyang","wuling"] },
        { id: "zhang_xiu", name: "张绣", faction: "宛城", color: "#DC2626", difficulty: "困难", desc: "宛城割据，骁勇善战",
            cities: ["wancheng","xinye","yongan"] },
        { id: "liu_zhang", name: "刘璋", faction: "益州", color: "#92400E", difficulty: "普通", desc: "暗弱之主，据守天府",
            cities: ["chengdu","mianzhu","zitong","jiangyou","langzhong","jiangzhou","baidi","wuyang"] },
        { id: "ma_teng", name: "马腾", faction: "西凉", color: "#57534E", difficulty: "困难", desc: "西凉铁骑，虎视中原",
            cities: ["tianshui","wudu","liangzhou","zhangye","jiuquan","dunhuang","anding","jieting","longxi","xicheng","qishan"] },
        { id: "zhang_lu", name: "张鲁", faction: "汉中", color: "#8B5CF6", difficulty: "困难", desc: "五斗米道，割据汉中",
            cities: ["hanzhong","yinping","jianmen","baishui"] },
        { id: "xiongnu", name: "南匈奴", faction: "匈奴", color: "#6B7280", difficulty: "极难", desc: "北方游牧，边患不断",
            cities: ["yinchuan","wuyuan"] },
        { id: "meng_huo", name: "孟获", faction: "南蛮", color: "#B45309", difficulty: "极难", desc: "南蛮王，偏远割据",
            cities: ["yunnan","jianning","yazhou"] },
        { id: "shi_xie", name: "士燮", faction: "交州", color: "#06B6D4", difficulty: "困难", desc: "交州太守，偏安一隅",
            cities: ["nanhai","guilin","jiaozhi"] }
    ],
        200: [
        { id: "cao_cao", name: "曹操", faction: "魏", color: "#7C3AED", difficulty: "简单", desc: "挟天子以令诸侯，官渡决战",
            cities: ["luoyang","chang_an","tongguan","wuguan","hongnong","hulao","wuzhangyuan","xianyang","chencang","hedong","yingchuan","guandu","runan","xuchang","qiaojun","baima","yanzhou","chenliu","dingtao","beihai","penglai","linzi","jinan","langya","xuzhou","xiapi","peixian","nanyang","wancheng","huaiyin","shouchun","hefei","wuhuan"] },
        { id: "yuan_shao", name: "袁绍", faction: "袁绍", color: "#4682B4", difficulty: "普通", desc: "河北霸主，四世三公",
            cities: ["ye","nanpi","jizhou_cheng","liyang","zhending","qinghe","bohai","pingyuan","beiping","jizhou","daijun","zhuojun","yuyang","pingcheng","yanmenguan","bingzhou","shangdang","shangjun","liaodong","lelang"] },
        { id: "liu_bei", name: "刘备", faction: "刘备", color: "#F4E04D", difficulty: "极难", desc: "依附袁绍后游击汝南",
            cities: ["xinye","shangyong","jiangxia","chibi"] },
        { id: "sun_quan", name: "孙权", faction: "吴", color: "#4CAF50", difficulty: "困难", desc: "新主继位，江东未稳",
            cities: ["jianye","wujun","kuaiji","caisang","danyang","lujiang","yuzhang","poyang","quanzhou","jianan","luling","yizhou","guangling","yiling"] },
        { id: "liu_biao", name: "刘表", faction: "荆州", color: "#009688", difficulty: "普通", desc: "荆州之主，守成之主",
            cities: ["xiangyang","jiangling","gongan","huarong","baqiu","changsha","guiyang","wuling"] },
        { id: "liu_zhang", name: "刘璋", faction: "益州", color: "#C41E3A", difficulty: "普通", desc: "暗弱之主，据守天府",
            cities: ["chengdu","mianzhu","zitong","jiangyou","langzhong","jiangzhou","baidi","wuyang"] },
        { id: "ma_teng", name: "马腾", faction: "西凉", color: "#57534E", difficulty: "困难", desc: "西凉铁骑，虎视中原",
            cities: ["tianshui","wudu","liangzhou","zhangye","jiuquan","dunhuang","anding","jieting","longxi","xicheng","qishan"] },
        { id: "zhang_lu", name: "张鲁", faction: "汉中", color: "#8B5CF6", difficulty: "困难", desc: "五斗米道，割据汉中",
            cities: ["hanzhong","jiamengguan","yinping","jianmen","baishui"] },
        { id: "xiongnu", name: "南匈奴", faction: "匈奴", color: "#6B7280", difficulty: "极难", desc: "北方游牧，边患不断",
            cities: ["yinchuan","wuyuan"] },
        { id: "meng_huo", name: "孟获", faction: "南蛮", color: "#B45309", difficulty: "极难", desc: "南蛮王，偏远割据",
            cities: ["yongan","yunnan","jianning"] },
        { id: "shi_xie", name: "士燮", faction: "交州", color: "#06B6D4", difficulty: "困难", desc: "交州太守，偏安一隅",
            cities: ["nanhai","guilin","jiaozhi","yazhou"] }
    ],
    208: [
        { id: "cao_cao", name: "曹操", faction: "魏", color: "#7C3AED", difficulty: "简单", desc: "大军南下，志在一统",
            cities: ["luoyang","chang_an","tongguan","wuguan","hongnong","hulao","wuzhangyuan","hedong","qinghe","nanpi","bohai","pingyuan","jizhou_cheng","ye","liyang","zhending","beiping","jizhou","daijun","zhuojun","yuyang","pingcheng","yanmenguan","bingzhou","shangdang","beihai","penglai","linzi","jinan","baima","yanzhou","chenliu","dingtao","yingchuan","guandu","runan","xuchang","qiaojun","langya","xuzhou","xiapi","nanyang","wancheng","xiangyang","huaiyin","peixian","shouchun","hefei","wuhuan"] },
        { id: "sun_quan", name: "孙权", faction: "吴", color: "#4CAF50", difficulty: "普通", desc: "据长江天险，虎踞江东",
            cities: ["jianye","wujun","kuaiji","caisang","danyang","lujiang","jiangling","huarong","gongan","yuzhang","poyang","quanzhou","jianan","luling","chibi","yizhou","guangling"] },
        { id: "liu_bei", name: "刘备", faction: "刘备", color: "#F4E04D", difficulty: "极难", desc: "败走新野，仁义之师",
            cities: ["xinye", "jiangxia"] },
        { id: "ma_teng", name: "马腾", faction: "西凉", color: "#57534E", difficulty: "困难", desc: "西凉铁骑，虎视中原",
            cities: ["tianshui","wudu","liangzhou","zhangye","jiuquan","dunhuang","xianyang","chencang","xicheng","shangjun","qishan","jieting","longxi","anding"] },
        { id: "liu_zhang", name: "刘璋", faction: "益州", color: "#C41E3A", difficulty: "普通", desc: "暗弱之主，据守天府",
            cities: ["chengdu","mianzhu","zitong","jiangyou","langzhong","jiangzhou","baidi","wuyang","shangyong","yiling"] },
        { id: "zhang_lu", name: "张鲁", faction: "汉中", color: "#8B5CF6", difficulty: "困难", desc: "五斗米道，割据汉中",
            cities: ["hanzhong","jiamengguan","yinping","jianmen","baishui"] },
        { id: "shi_xie", name: "士燮", faction: "交州", color: "#06B6D4", difficulty: "困难", desc: "交州太守，偏安一隅",
            cities: ["nanhai","guilin","jiaozhi","yazhou"] },
        { id: "gongsun_kang", name: "公孙康", faction: "辽东", color: "#6B7280", difficulty: "极难", desc: "辽东太守，名义臣服",
            cities: ["liaodong","lelang"] },
        { id: "xiongnu", name: "南匈奴", faction: "匈奴", color: "#78716C", difficulty: "极难", desc: "北方游牧，边患不断",
            cities: ["yinchuan","wuyuan"] },
        { id: "meng_huo", name: "孟获", faction: "南蛮", color: "#B45309", difficulty: "极难", desc: "南蛮王，偏远割据",
            cities: ["yongan","yunnan","jianning"] },
        { id: "han_xuan", name: "韩玄", faction: "长沙", color: "#F59E0B", difficulty: "极难", desc: "长沙太守",
            cities: ["changsha"] },
        { id: "jin_xuan", name: "金旋", faction: "武陵", color: "#A3E635", difficulty: "极难", desc: "武陵太守",
            cities: ["wuling"] },
        { id: "zhao_fan", name: "赵范", faction: "桂阳", color: "#34D399", difficulty: "极难", desc: "桂阳太守",
            cities: ["guiyang"] },
        { id: "liu_biao_remnant", name: "刘表旧部", faction: "巴丘", color: "#FBBF24", difficulty: "极难", desc: "刘表残部",
            cities: ["baqiu"] }
    ],
    220: [
        { id: "cao_pi", name: "曹丕", faction: "魏", color: "#7C3AED", difficulty: "简单", desc: "中原正统，坐拥天下大半",
            cities: ["luoyang","chang_an","tongguan","wuguan","hongnong","hulao","wuzhangyuan","xianyang","chencang","hedong","qinghe","nanpi","bohai","pingyuan","jizhou_cheng","ye","liyang","zhending","beiping","jizhou","daijun","zhuojun","lelang","yuyang","liaodong","wuhuan","pingcheng","yanmenguan","bingzhou","shangdang","shangjun","beihai","penglai","linzi","jinan","baima","yanzhou","chenliu","dingtao","yingchuan","guandu","runan","xuchang","qiaojun","langya","xuzhou","xiapi","peixian","qishan","tianshui","wudu","longxi","liangzhou","zhangye","jiuquan","dunhuang","jieting","anding","xicheng","nanyang","wancheng","xinye","shangyong","shouchun","hefei","xiangyang","huaiyin"] },
        { id: "liu_bei", name: "刘备", faction: "蜀", color: "#F4E04D", difficulty: "极难", desc: "失荆州、折关羽，仅余益州",
            cities: ["hanzhong","jiamengguan","yinping","chengdu","baishui","mianzhu","zitong","jianmen","jiangyou","langzhong","jiangzhou","baidi","wuyang"] },
        { id: "sun_quan", name: "孙权", faction: "吴", color: "#4CAF50", difficulty: "困难", desc: "袭取荆州，依附曹魏",
            cities: ["jianye","lujiang","wujun","kuaiji","caisang","danyang","poyang","jianan","luling","yuzhang","quanzhou","yiling","jiangling","gongan","huarong","baqiu","changsha","guiyang","wuling","nanhai","yazhou","guilin","jiaozhi","guangling","chibi","yizhou","jiangxia"] },
        { id: "meng_huo", name: "孟获", faction: "南蛮", color: "#B45309", difficulty: "极难", desc: "南蛮王，偏远割据",
            cities: ["jianning","yunnan","yongan"] },
        { id: "xiongnu", name: "南匈奴", faction: "匈奴", color: "#6B7280", difficulty: "极难", desc: "南匈奴单于，北方边患",
            cities: ["yinchuan","wuyuan"] }
    ],
    215: [
        { id: "cao_cao", name: "曹操", faction: "魏", color: "#7C3AED", difficulty: "简单", desc: "如日中天，志在一统",
            cities: ["luoyang","chang_an","tongguan","wuguan","hongnong","hulao","wuzhangyuan","hedong","qinghe","nanpi","bohai","pingyuan","jizhou_cheng","ye","liyang","zhending","beiping","jizhou","daijun","zhuojun","yuyang","pingcheng","yanmenguan","bingzhou","shangdang","shangjun","beihai","penglai","linzi","jinan","baima","yanzhou","chenliu","dingtao","yingchuan","guandu","runan","xuchang","qiaojun","langya","xuzhou","xiapi","peixian","anding","jieting","qishan","longxi","xicheng","huaiyin","shouchun","hefei","nanyang","wancheng","xiangyang","xinye","wuhuan","xianyang","chencang"] },
        { id: "liu_bei", name: "刘备", faction: "蜀", color: "#F4E04D", difficulty: "普通", desc: "刚取益州，元气初复",
            cities: ["chengdu","mianzhu","zitong","jiangyou","langzhong","jiangzhou","baidi","wuyang","jianmen","hanzhong","jiamengguan","yinping","baishui","shangyong","yiling","jiangling","gongan","huarong","jiangxia","baqiu","wuling"] },
        { id: "sun_quan", name: "孙权", faction: "吴", color: "#4CAF50", difficulty: "普通", desc: "湘水划界，虎踞江东",
            cities: ["jianye","wujun","kuaiji","caisang","danyang","lujiang","yuzhang","poyang","quanzhou","jianan","luling","yizhou","guangling","chibi","changsha","guiyang"] },
        { id: "ma_chao", name: "马超", faction: "西凉", color: "#57534E", difficulty: "困难", desc: "西凉锦马超，虎视中原",
            cities: ["tianshui","wudu","liangzhou","zhangye","jiuquan","dunhuang","yinchuan","wuyuan"] },
        { id: "gongsun_kang", name: "公孙康", faction: "辽东", color: "#6B7280", difficulty: "极难", desc: "辽东太守，名义臣服",
            cities: ["liaodong","lelang"] },
        { id: "meng_huo", name: "孟获", faction: "南蛮", color: "#B45309", difficulty: "极难", desc: "南蛮王，偏远割据",
            cities: ["yongan","yunnan","jianning"] },
        { id: "shi_xie", name: "士燮", faction: "交州", color: "#06B6D4", difficulty: "困难", desc: "交州太守，偏安一隅",
            cities: ["nanhai","guilin","jiaozhi","yazhou"] }
    ],
        263: [
        { id: "simayi", name: "司马昭", faction: "魏", color: "#7C3AED", difficulty: "简单", desc: "三路伐蜀，势如破竹",
            cities: ["luoyang","chang_an","tongguan","wuguan","hongnong","hulao","wuzhangyuan","xianyang","chencang","hedong","qinghe","nanpi","bohai","pingyuan","jizhou_cheng","ye","liyang","zhending","beiping","jizhou","daijun","zhuojun","yuyang","pingcheng","yanmenguan","bingzhou","shangdang","shangjun","wuyuan","beihai","penglai","linzi","jinan","baima","yanzhou","chenliu","dingtao","yingchuan","guandu","runan","xuchang","qiaojun","langya","xuzhou","xiapi","peixian","huaiyin","shouchun","hefei","guangling","nanyang","wancheng","xiangyang","xinye","shangyong","jiangling","tianshui","wudu","liangzhou","zhangye","jiuquan","dunhuang","yinchuan","anding","jieting","qishan","longxi","xicheng","hanzhong","jiamengguan","yinping","baishui","jianmen","wuhuan"] },
        { id: "liu_shan", name: "刘禅", faction: "蜀", color: "#F4E04D", difficulty: "极难", desc: "后主昏庸，国势日衰",
            cities: ["chengdu","mianzhu","zitong","jiangyou","langzhong","jiangzhou","baidi","wuyang","yongan","yunnan","jianning"] },
        { id: "sun_hao", name: "孙皓", faction: "吴", color: "#4CAF50", difficulty: "困难", desc: "暴君治国，自顾不暇",
            cities: ["jianye","wujun","kuaiji","caisang","danyang","lujiang","yuzhang","poyang","quanzhou","jianan","luling","yizhou","nanhai","guilin","jiaozhi","yazhou","yiling","jiangxia","huarong","chibi","baqiu","gongan","changsha","wuling","guiyang"] },
        { id: "gongsun_yuan", name: "公孙渊", faction: "辽东", color: "#6B7280", difficulty: "极难", desc: "辽东割据，自保为主",
            cities: ["liaodong","lelang"] }
    ],    249: [
        { id: "simayi", name: "司马懿", faction: "魏", color: "#7C3AED", difficulty: "简单", desc: "高平陵之变，掌控朝政",
            cities: ["luoyang","chang_an","tongguan","wuguan","hongnong","hulao","wuzhangyuan","xianyang","chencang","baima","yanzhou","chenliu","dingtao","yingchuan","guandu","xuchang","qiaojun","penglai","linzi","jinan","langya","beihai","xuzhou","peixian","ye","nanpi","jizhou_cheng","qinghe","bohai","pingyuan","beiping","jizhou","daijun","zhuojun","pingcheng","yanmenguan","bingzhou","wuhuan","nanyang","wancheng","xinye","xiapi","yuyang","liaodong","lelang","hedong","liyang","zhending","shangjun","zhangye","jiuquan","dunhuang","liangzhou","longxi","anding","tianshui","wudu","qishan","jieting","shangdang","xicheng","xiangyang"] },
        { id: "sun_quan", name: "孙权", faction: "吴", color: "#4CAF50", difficulty: "困难", desc: "东吴大帝，虎踞江东",
            cities: ["jianye","wujun","kuaiji","caisang","danyang","yuzhang","poyang","luling","jianan","quanzhou","yizhou","jiangling","gongan","huarong","baqiu","changsha","guiyang","wuling","nanhai","guilin","jiaozhi","yazhou","yiling","chibi","jiangxia","guangling"] },
        { id: "liu_shan", name: "刘禅", faction: "蜀", color: "#F4E04D", difficulty: "极难", desc: "蜀汉后主，北伐中原",
            cities: ["chengdu","mianzhu","zitong","jiangyou","langzhong","baidi","wuyang","hanzhong","jiamengguan","yinping","jianmen","baishui","jiangzhou","shangyong","jianning","yunnan","yongan"] },
        { id: "wang_ling", name: "王凌", faction: "淮南", color: "#DC2626", difficulty: "极难", desc: "淮南一叛，据守寿春",
            cities: ["shouchun","hefei","lujiang","runan","huaiyin"] },
        { id: "xiongnu", name: "南匈奴", faction: "匈奴", color: "#6B7280", difficulty: "极难", desc: "北方游牧，边患不断",
            cities: ["yinchuan","wuyuan"] }
    ]
};
